version: '3.9'

services:
  db:
    # container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: peche
    ports:
      - "5436:5432"
  # pgadmin:
  #   # container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5051:80"
  back:
    build: ./back
    ports:
      - "3001:3000"
    volumes:
      - ./back:/usr/src/app
      - back_node_modules:/usr/src/app/node_modules
    env_file:
      - ./back/.env

  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
      - front_node_modules:/usr/src/app/node_modules

volumes:
  back_node_modules:
  front_node_modules: